// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1VEAps5QT1caLs-NE2nIx1PEMiZ36jM',
    appId: '1:561113886059:web:db7b11d69905c8e7cdb02e',
    messagingSenderId: '561113886059',
    projectId: 'ins-flutter-92e18',
    authDomain: 'ins-flutter-92e18.firebaseapp.com',
    databaseURL: 'https://ins-flutter-92e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ins-flutter-92e18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5KAlqt_2ebNPGTkXtcJvAEXhB0oAte0',
    appId: '1:561113886059:android:49bb8bc22c515613cdb02e',
    messagingSenderId: '561113886059',
    projectId: 'ins-flutter-92e18',
    databaseURL: 'https://ins-flutter-92e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ins-flutter-92e18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcQ9g75UYb1UW-Uj4YerJqHMQ48iV6QE',
    appId: '1:561113886059:ios:e367cb2df8e2e570cdb02e',
    messagingSenderId: '561113886059',
    projectId: 'ins-flutter-92e18',
    databaseURL: 'https://ins-flutter-92e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ins-flutter-92e18.appspot.com',
    iosClientId: '561113886059-j4rc9bhgjaesgb6h0208468fjj3fsebl.apps.googleusercontent.com',
    iosBundleId: 'com.example.insFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcQ9g75UYb1UW-Uj4YerJqHMQ48iV6QE',
    appId: '1:561113886059:ios:e367cb2df8e2e570cdb02e',
    messagingSenderId: '561113886059',
    projectId: 'ins-flutter-92e18',
    databaseURL: 'https://ins-flutter-92e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ins-flutter-92e18.appspot.com',
    iosClientId: '561113886059-j4rc9bhgjaesgb6h0208468fjj3fsebl.apps.googleusercontent.com',
    iosBundleId: 'com.example.insFlutter',
  );
}
